# Generated by Django 5.0.6 on 2026-06-24 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('WAITING', 'Waiting'), ('COUNTDOWN', 'Countdown'), ('RUNNING', 'Running'), ('CRASHED', 'Crashed')], default='WAITING', max_length=20)),
                ('crash_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('server_seed', models.CharField(blank=True, max_length=64)),
                ('client_seed', models.CharField(blank=True, max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('hash_result', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'created_at'], name='simulation__state_e16731_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('auto_cashout_at', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_cashed_out', models.BooleanField(default=False)),
                ('cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simulation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='simulation.simulationround')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation_round', 'user'], name='simulation__simulat_649a91_idx')],
            },
        ),
    ]
